version: '3.8'

services:
  # 1. Serwer bazy danych PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: gra66_postgres
    environment:
      POSTGRES_USER: gra66user
      POSTGRES_PASSWORD: gra66password
      POSTGRES_DB: gra66db
    ports:
      - "5432:5432" # Udostępnij port 5432 na localhost
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Użyj folderu z projektu

  # 2. Serwer Redis
  redis:
    image: redis:7-alpine
    container_name: gra66_redis
    ports:
      - "6379:6379" # Udostępnij port 6379 na localhost

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}/postgres-data'